name: flutter_ringtone_player
description: A simple player for system default ringtones, alarms and notifications
<<<<<<< HEAD
version: 4.1.0
=======
version: 4.1.1
>>>>>>> 5e46534d0f7f95af3f6c6a5f10ad21ef0686978e
homepage: https://github.com/inway/flutter_ringtone_player
repository: https://github.com/inway/flutter_ringtone_player

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  cider: ^0.2.8
  path_provider: ^2.1.1
  plugin_platform_interface: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.inway.ringtone.player
        pluginClass: FlutterRingtonePlayerPlugin
      ios:
        pluginClass: FlutterRingtonePlayerPlugin
